#!/bin/sh
# herdr-kitten installer for non-nix hosts (spec 1.1). Copies files; never edits configs.
#
# INSTALLED LAYOUT (round2-02 — BUG-3, BUG-15)
#
#   ~/.config/kitty/hk/            the kitten tree, a DIRECTORY and a package
#     __init__.py                  (generated) the package marker — see below
#     hk.py                        the kitten kitty loads: `kitten hk/hk.py`
#     ladder.py  fork_state.py     the kitten's own flat modules
#     predicate.py  config.py      vendored copies: nothing under kitten/ ever
#                                  says `from hk import ...` (BUG-3)
#     assets/                      fork.lua, the trampoline, the spinner
#   ~/.config/kitty/hk-maps.conf   the suggested maps, to `include` from kitty.conf
#   ~/.local/share/hk/hk/*.py      the CLI package
#   ~/.local/share/hk/bin/hk       the CLI (bin/hk resolves ../hk of its realpath)
#   ~/.local/bin/hk                a symlink onto it
#   ~/.config/hk/config.toml       the template, only when absent
#
# WHY A SUBDIRECTORY, AND WHY IT IS NAMED `hk`
#
# kitty's custom-kitten loader inserts the kitten's own directory at sys.path[0]
# (kittens/runner.py:57-58). The old layout dropped `hk.py`, `ladder.py` and
# `fork_state.py` loose into ~/.config/kitty/, so that entry was the whole kitty
# config dir and the module file `hk.py` shadowed the `hk` PACKAGE — every
# `from hk import ...` on the kitten side resolved to the kitten itself and
# raised ImportError. No gesture ever dispatched from an installed tree.
#
# So the tree moves into one directory (BUG-15: nothing loose in the kitty
# config dir), and that directory is named `hk` and carries an __init__.py.
# The name is the point: `hk` is the one name anything looking from the kitty
# config dir will reach for, and it now resolves to a package DIRECTORY that
# cannot be shadowed by a stray module file. `sys.path` gets a directory whose
# own name is `hk`, and the kitten's flat neighbours (ladder, fork_state) import
# by their own names, as they always did.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BIN_DIR="${HK_BIN_DIR:-$HOME/.local/bin}"
KITTY_DIR="${HK_KITTY_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/kitty}"
HK_CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hk"
SHARE_DIR="${HK_SHARE_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/hk}"
KITTEN_DIR="$KITTY_DIR/hk"
MAPS_FILE="$KITTY_DIR/hk-maps.conf"

command -v python3 >/dev/null 2>&1 || { echo "install.sh: python3 >= 3.11 required" >&2; exit 1; }
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)' \
  || { echo "install.sh: python3 >= 3.11 required (tomllib)" >&2; exit 1; }

install_file() {  # install_file <src> <dst> [chmod-mode]
  mkdir -p -- "$(dirname -- "$2")"
  cp -- "$1" "$2"
  if [ -n "${3:-}" ]; then chmod "$3" "$2"; fi
}

# ---- the CLI ---------------------------------------------------------------
# *.py only: never copy __pycache__ into a user's install.
for src in "$HERE"/hk/*.py; do
  install_file "$src" "$SHARE_DIR/hk/$(basename -- "$src")"
done
install_file "$HERE/bin/hk" "$SHARE_DIR/bin/hk" 755
mkdir -p -- "$BIN_DIR"
ln -sf "$SHARE_DIR/bin/hk" "$BIN_DIR/hk"

# ---- the kitten tree -------------------------------------------------------
for name in hk.py ladder.py fork_state.py; do
  install_file "$HERE/kitten/$name" "$KITTEN_DIR/$name"
done
# Vendored beside the kitten: ladder.py loads predicate.py BY PATH and hk.py
# loads config.py BY PATH, so the kitten tree is self-contained and the `hk`
# name is never looked up from inside it (BUG-3).
install_file "$HERE/hk/predicate.py" "$KITTEN_DIR/predicate.py"
install_file "$HERE/hk/config.py" "$KITTEN_DIR/config.py"
for src in "$HERE"/assets/*; do
  install_file "$src" "$KITTEN_DIR/assets/$(basename -- "$src")"
done
cat > "$KITTEN_DIR/__init__.py" <<'PY'
"""Package marker for the installed herdr-kitten tree (generated by install.sh).

This directory is `hk` under the kitty config directory. The marker is what
makes `hk` a package there rather than a name a loose `hk.py` could claim:
that shadowing is BUG-3, the reason no gesture dispatched from an installed
tree before round2-02. Nothing imports this module; deleting it re-opens the
hole. The kitten itself is hk.py beside this file, loaded by kitty as
`kitten hk/hk.py`.
"""
PY

# the maps live beside the kitten so `include hk-maps.conf` in kitty.conf is
# the whole wiring step, and its relative kitten path resolves from there
install_file "$HERE/conf/kitty-maps.conf" "$MAPS_FILE"

# ---- config template, only if absent (never clobber user config) -----------
if [ -e "$HK_CONF_DIR/config.toml" ]; then
  echo "kept: $HK_CONF_DIR/config.toml (already yours; template not copied)"
else
  install_file "$HERE/conf/config.toml" "$HK_CONF_DIR/config.toml"
fi

echo "installed:"
echo "  $BIN_DIR/hk -> $SHARE_DIR/bin/hk"
echo "  $KITTEN_DIR/  (kitten: 'kitten hk/hk.py')"
echo "  $MAPS_FILE"
echo "wire it up: add   include hk-maps.conf   to $KITTY_DIR/kitty.conf"
echo "herdr profile snippet to merge by hand: $HERE/conf/herdr-profile.toml"
"$BIN_DIR/hk" --version
